/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file ".s21_test.kek" instead.
 */

#include <check.h>
#include <string.h>

#include "../s21_string.h"

START_TEST(strlen_test) {
#line 6
  char str1[30] = "day\n";
  char str2[30] = "An awf\tul day";
  char str3[30] = "Wiggam's aw\0ful day";
  char str4[30] = "3 4 ";
  char str5[30] = "1 2 3 4 5 ";
  char str6[30] = "";

  ck_assert_int_eq(s21_strlen(str1), strlen(str1));
  ck_assert_int_eq(s21_strlen(str2), strlen(str2));
  ck_assert_int_eq(s21_strlen(str3), strlen(str3));
  ck_assert_int_eq(s21_strlen(str4), strlen(str4));
  ck_assert_int_eq(s21_strlen(str5), strlen(str5));
  ck_assert_int_eq(s21_strlen(str6), strlen(str6));
}
END_TEST

START_TEST(strncpy_test) {
#line 95
  char str1[30] = "";
  char str2[30] = " ";
  char str3[30] = "One ice-cream";
  char str4[30] = "One\nice-cream";
  char str5[30] = "One\0ice-cream";
  char str6[30] = "One\tice-cream";
  char str7[30] = "Love";
  ck_assert_pstr_eq(strncpy(str1, str3, 15), s21_strncpy(str1, str3, 15));
  ck_assert_pstr_eq(strncpy(str2, str3, 14), s21_strncpy(str2, str3, 14));
  ck_assert_pstr_eq(strncpy(str3, str7, 4), s21_strncpy(str3, str7, 4));
  ck_assert_pstr_eq(strncpy(str3, str4, 7), s21_strncpy(str3, str4, 7));
  ck_assert_pstr_eq(strncpy(str4, str7, 4), s21_strncpy(str4, str7, 4));
  ck_assert_pstr_eq(strncpy(str5, str7, 4), s21_strncpy(str5, str7, 4));
  ck_assert_pstr_eq(strncpy(str5, str3, 9), s21_strncpy(str5, str3, 9));
  ck_assert_pstr_eq(strncpy(str6, str7, 4), s21_strncpy(str6, str7, 4));
  ck_assert_pstr_eq(strncpy(str7, str2, 4), s21_strncpy(str7, str2, 4));
}
END_TEST

START_TEST(memcpy_test) {
#line 113
  char str1[30] = "";
  char str2[30] = " ";
  char str3[30] = "One ice-cream";
  char str4[30] = "One\nice-cream";
  char str5[30] = "One\0ice-cream";
  char str6[30] = "One\tice-cream";
  char str7[30] = "Love";
  ck_assert_pstr_eq(memcpy(str1, str3, 5), s21_memcpy(str1, str3, 5));
  ck_assert_pstr_eq(memcpy(str2, str3, 5), s21_memcpy(str2, str3, 5));
  ck_assert_pstr_eq(memcpy(str3, str7, 4), s21_memcpy(str3, str7, 4));
  ck_assert_pstr_eq(memcpy(str3, str4, 7), s21_memcpy(str3, str4, 7));
  ck_assert_pstr_eq(memcpy(str3, str4, 0), s21_memcpy(str3, str4, 0));
  ck_assert_pstr_eq(memcpy(str4, str7, 4), s21_memcpy(str4, str7, 4));
  ck_assert_pstr_eq(memcpy(str5, str7, 4), s21_memcpy(str5, str7, 4));
  ck_assert_pstr_eq(memcpy(str5, str3, 9), s21_memcpy(str5, str3, 9));
  ck_assert_pstr_eq(memcpy(str6, str7, 4), s21_memcpy(str6, str7, 4));
  ck_assert_pstr_eq(memcpy(str7, str2, 4), s21_memcpy(str7, str2, 4));
}
END_TEST

START_TEST(memset_test) {
#line 133
  char str1[30] = "";
  char str2[30] = " ";
  char str3[30] = "One ice-cream";
  char str4[30] = "One\nice-cream";
  char str5[30] = "One\0ice-cream";
  char str6[30] = "One\tice-cream";
  ck_assert_pstr_eq(memset(str1, '5', 1), s21_memset(str1, '5', 1));
  ck_assert_pstr_eq(memset(str2, '5', 1), s21_memset(str2, '5', 1));
  ck_assert_pstr_eq(memset(str3, '1', 3), s21_memset(str3, '1', 3));
  ck_assert_pstr_eq(memset(str3, '7', 7), s21_memset(str3, '7', 7));
  ck_assert_pstr_eq(memset(str3, '\t', 3), s21_memset(str3, '\t', 3));
  ck_assert_pstr_eq(memset(str3, 'U', 3), s21_memset(str3, 'U', 3));
  ck_assert_pstr_eq(memset(str3, '^', 7), s21_memset(str3, '^', 7));
  ck_assert_pstr_eq(memset(str4, '7', 7), s21_memset(str4, '7', 7));
  ck_assert_pstr_eq(memset(str4, '\t', 1), s21_memset(str4, '\t', 1));
  ck_assert_pstr_eq(memset(str4, 'U', 7), s21_memset(str4, 'U', 7));
  ck_assert_pstr_eq(memset(str4, '^', 7), s21_memset(str4, '^', 7));
  ck_assert_pstr_eq(memset(str5, '7', 7), s21_memset(str5, '7', 7));
  ck_assert_pstr_eq(memset(str5, '\t', 1), s21_memset(str5, '\t', 1));
  ck_assert_pstr_eq(memset(str5, 'U', 7), s21_memset(str5, 'U', 7));
  ck_assert_pstr_eq(memset(str5, '^', 7), s21_memset(str5, '^', 7));
  ck_assert_pstr_eq(memset(str6, '7', 7), s21_memset(str5, '7', 7));
  ck_assert_pstr_eq(memset(str6, '\t', 1), s21_memset(str6, '\t', 1));
  ck_assert_pstr_eq(memset(str6, 'U', 7), s21_memset(str6, 'U', 7));
  ck_assert_pstr_eq(memset(str6, '^', 7), s21_memset(str6, '^', 7));
}
END_TEST

START_TEST(strchr_test) {
  #line 187
    char *str1 = "ice-cream clean line";
    char *str2 = "ice-cream\tclean line";
    char *str3 = "ice-cream\nclean line";
    char *str4 = "ice-cream\0clean line";
    char *str5 = "";
    char *str6 = "\0";
    char *str7 = " ";
    ck_assert_pstr_eq(strchr(str1, 'c'), s21_strchr(str1, 'c'));
    ck_assert_pstr_eq(strchr(str1, 'f'), s21_strchr(str1, 'f'));
    ck_assert_pstr_eq(strchr(str1, ' '), s21_strchr(str1, ' '));
    ck_assert_pstr_eq(strchr(str1, 'a'), s21_strchr(str1, 'a'));
    ck_assert_pstr_eq(strchr(str2, '\t'), s21_strchr(str2, '\t'));
    ck_assert_pstr_eq(strchr(str3, '\n'), s21_strchr(str3, '\n'));
    ck_assert_pstr_eq(strchr(str1, 'e'), s21_strchr(str1, 'e'));
    ck_assert_pstr_eq(strchr(str4, '\0'), s21_strchr(str4, '\0'));
    ck_assert_pstr_eq(strchr(str5, 'c'), s21_strchr(str5, 'c'));
    ck_assert_pstr_eq(strchr(str6, 'c'), s21_strchr(str6, 'c'));
    ck_assert_pstr_eq(strchr(str7, 'c'), s21_strchr(str7, 'c'));
  }
  END_TEST

/* bonus_testing
START_TEST(suite_to_lower) {
  char str[] = "ONE ICE-CREAM";
  char str2[] = "ONE\nICE-CREAM";
  char str3[] = "N";
  char str4[] = "One\tice-cream";
  char str5[] = " \0";
  char str6[] = "\n";
  char str7[] = "\0";
  char str8[] = "One ICe-cREam";
  char str9[] = "";
  char *str10 = s21_NULL;

  char *res1 = s21_to_lower(str);
  char *res2 = s21_to_lower(str2);
  char *res3 = s21_to_lower(str3);
  char *res4 = s21_to_lower(str4);
  char *res5 = s21_to_lower(str5);
  char *res6 = s21_to_lower(str6);
  char *res7 = s21_to_lower(str7);
  char *res8 = s21_to_lower(str8);
  char *res9 = s21_to_lower(str9);
  char *res10 = s21_to_lower(str10);

  ck_assert_str_eq(res1, "one ice-cream");
  free(res1);
  ck_assert_str_eq(res2, "one\nice-cream");
  free(res2);
  ck_assert_str_eq(res3, "n");
  free(res3);
  ck_assert_str_eq(res4, "one\tice-cream");
  free(res4);
  ck_assert_str_eq(res5, " ");
  free(res5);
  ck_assert_str_eq(res6, "\n");
  free(res6);
  ck_assert_str_eq(res7, "");
  free(res7);
  ck_assert_str_eq(res8, "one ice-cream");
  free(res8);
  ck_assert_pstr_eq(res9, "");
  free(res9);
  ck_assert_pstr_eq(res10, s21_NULL);
  free(res10);
}
END_TEST

START_TEST(suite_to_upper) {
  char str[] = "One ice-cream";
  char str2[] = "One\nice-cream";
  char str3[] = "a";
  char str4[] = "One\tice-cream";
  char str5[] = " \0";
  char str6[] = "\n";
  char str7[] = "\0";
  char str8[] = "One ICe-cREam";
  char str9[] = "";
  char *str10 = s21_NULL;

  char *res1 = s21_to_upper(str);
  char *res2 = s21_to_upper(str2);
  char *res3 = s21_to_upper(str3);
  char *res4 = s21_to_upper(str4);
  char *res5 = s21_to_upper(str5);
  char *res6 = s21_to_upper(str6);
  char *res7 = s21_to_upper(str7);
  char *res8 = s21_to_upper(str8);
  char *res9 = s21_to_upper(str9);
  char *res10 = s21_to_upper(str10);

  ck_assert_str_eq(res1, "ONE ICE-CREAM");
  free(res1);
  ck_assert_str_eq(res2, "ONE\nICE-CREAM");
  free(res2);
  ck_assert_str_eq(res3, "A");
  free(res3);
  ck_assert_str_eq(res4, "ONE\tICE-CREAM");
  free(res4);
  ck_assert_str_eq(res5, " ");
  free(res5);
  ck_assert_str_eq(res6, "\n");
  free(res6);
  ck_assert_str_eq(res7, "");
  free(res7);
  ck_assert_str_eq(res8, "ONE ICE-CREAM");
  free(res8);
  ck_assert_pstr_eq(res9, "");
  free(res9);
  ck_assert_pstr_eq(res10, s21_NULL);
  free(res10);
}
END_TEST

START_TEST(suite_insert) {
  char *s1 = "One ice-cream";
  char *s2 = "or two";
  char *s3 = " ";
  char *s4 = "";
  char *s5 = "\0";
  char *s6 = s21_NULL;
  char *res1 = s21_insert(s1, " ", 2);
  char *res2 = s21_insert(s1, s2, 13);
  char *res3 = s21_insert(s1, s2, 0);
  char *res4 = s21_insert(s1, s3, 5);
  char *res5 = s21_insert(s2, s1, 4);
  char *res6 = s21_insert(s1, s2, 2);
  char *res7 = s21_insert(s3, s2, 1);
  char *res8 = s21_insert(s4, s2, 1);
  char *res9 = s21_insert(s5, s2, 1);
  char *res10 = s21_insert(s1, s5, 1);
  char *res11 = s21_insert(s1, s4, 1);
  char *res12 = s21_insert(s6, s21_NULL, 1);
  char *res13 = s21_insert(s1, s21_NULL, 1);

  ck_assert_str_eq(res1, "On e ice-cream");
  free(res1);
  ck_assert_str_eq(res2, "One ice-creamor two");
  free(res2);
  ck_assert_str_eq(res3, "or twoOne ice-cream");
  free(res3);
  ck_assert_str_eq(res4, "One i ce-cream");
  free(res4);
  ck_assert_str_eq(res5, "or tOne ice-creamwo");
  free(res5);
  ck_assert_str_eq(res6, "Onor twoe ice-cream");
  free(res6);
  ck_assert_str_eq(res7, " or two");
  free(res7);
  ck_assert_pstr_eq(res8, s21_NULL);
  free(res8);
  ck_assert_pstr_eq(res9, s21_NULL);
  free(res9);
  ck_assert_pstr_eq(res10, "One ice-cream");
  free(res10);
  ck_assert_pstr_eq(res11, "One ice-cream");
  free(res11);
  ck_assert_pstr_eq(res12, s21_NULL);
  free(res12);
  ck_assert_pstr_eq(res13, s21_NULL);
  free(res13);
}
END_TEST

START_TEST(suite_trim) {
  char s1[30] = "-?One ice-cream!-?";
  char s3[30] = "";
  char s4[30] = "One ice-cream";
  char *s5 = s21_NULL;
  char s6[30] = "cream";
  char s7[30] = " One ice-cream ";
  char s8[30] = "One ice-cream!";
  char s9[30] = "e ice-cre";

  char *res1 = s21_trim(s5, s3);
  char *res2 = s21_trim(s1, "!?-");
  char *res3 = s21_trim(s3, "");
  char *res4 = s21_trim(s5, s21_NULL);
  char *res5 = s21_trim(s6, "123");
  char *res6 = s21_trim(s7, s3);
  char *res7 = s21_trim(s7, s5);
  char *res8 = s21_trim(s8, "!?-");
  char *res9 = s21_trim(s4, "Onam");
  char *res10 = s21_trim(s4, "love");
  char *res11 = s21_trim(s4, "One ice-cream");

  ck_assert_pstr_eq(s5, res1);
  free(res1);
  ck_assert_str_eq(s4, res2);
  free(res2);
  ck_assert_str_eq(s3, res3);
  free(res3);
  ck_assert_pstr_eq(s5, res4);
  free(res4);
  ck_assert_str_eq(s6, res5);
  free(res5);
  ck_assert_str_eq(s4, res6);
  free(res6);
  ck_assert_str_eq(s4, res7);
  free(res7);
  ck_assert_str_eq(s4, res8);
  free(res8);
  ck_assert_str_eq(s9, res9);
  free(res9);
  ck_assert_str_eq(s4, res10);
  free(res10);
  ck_assert_str_eq(s3, res11);
  free(res11);
}
END_TEST
*/

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  /* User-specified pre-run code */
#line 314
  srunner_set_fork_status(sr, CK_NOFORK);
  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, strlen_test);  
  tcase_add_test(tc1_1, strncpy_test);
  tcase_add_test(tc1_1, memcpy_test);
  tcase_add_test(tc1_1, memset_test);  
  tcase_add_test(tc1_1, strchr_test);
  
  
 

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
